version: "3"
services:
  servidorweb:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/local/tomcat/webapps
    depends_on:
      - "bbdd"

  bbdd:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: almacen
      MYSQL_ROOT_PASSWORD: secretone
      MYSQL_USER: almacen_user
      MYSQL_PASSWORD: onlyforyoureyes
    volumes:
      - ./.db_data:/var/lib/mysql
      - ./.db_backup:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    environment:
      PMA_HOST: "bbdd"
      PMA_USER: "root"
      PMA_PASSWORD: "secretone"
    depends_on:
      - "bbdd"
    ports:
      - "8081:80"
